# Generated by Django 3.2 on 2022-02-07 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerUser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
