# Generated by Django 3.2 on 2022-02-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('E', 'Educator'), ('S', 'Student')], default='S', max_length=1),
        ),
    ]
