# Generated by Django 3.2 on 2022-02-07 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(default='', max_length=120)),
                ('module_desc', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(default='', max_length=100)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('module_sel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testBuilder.module')),
            ],
        ),
        migrations.CreateModel(
            name='quizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.IntegerField(default=0)),
                ('wrong', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('grade', models.CharField(default='', max_length=10)),
                ('a_time', models.DateTimeField(auto_now=True)),
                ('attempted_time', models.DateTimeField(auto_now_add=True)),
                ('attempted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('linked_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testBuilder.module')),
                ('linked_test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testBuilder.test')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(default='', max_length=500)),
                ('op1', models.CharField(default='', max_length=300)),
                ('op2', models.CharField(default='', max_length=300)),
                ('op3', models.CharField(default='', max_length=300)),
                ('op4', models.CharField(default='', max_length=300)),
                ('answ', models.CharField(default='', help_text='Input option1 for the first option, option2 for the second option', max_length=300)),
                ('test_sel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testBuilder.test')),
            ],
        ),
    ]
