# Generated by Django 3.2 on 2022-01-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.CharField(max_length=120)),
                ('moduleDesc', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='addTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testName', models.CharField(max_length=100)),
                ('testDate', models.DateTimeField()),
            ],
        ),
    ]
