# Generated by Django 3.2 on 2022-02-08 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='linked_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testBuilder.module'),
        ),
    ]
