# Generated by Django 3.2 on 2022-01-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmodule',
            old_name='moduleDesc',
            new_name='mod_desc',
        ),
        migrations.RenameField(
            model_name='addmodule',
            old_name='moduleName',
            new_name='mod_name',
        ),
        migrations.RenameField(
            model_name='addtest',
            old_name='testDate',
            new_name='test_date',
        ),
        migrations.RenameField(
            model_name='addtest',
            old_name='testName',
            new_name='test_name',
        ),
    ]
