# Generated by Django 3.2 on 2022-02-09 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testBuilder', '0002_quizresult_linked_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='attempted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='linked_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testBuilder.module'),
        ),
    ]
