# Generated by Django 3.2 on 2022-01-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0002_auto_20220120_1339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addModule',
            new_name='Modules',
        ),
        migrations.RenameModel(
            old_name='addTest',
            new_name='Tests',
        ),
        migrations.RenameField(
            model_name='modules',
            old_name='mod_desc',
            new_name='module_desc',
        ),
        migrations.RenameField(
            model_name='modules',
            old_name='mod_name',
            new_name='module_name',
        ),
    ]
