# Generated by Django 3.2 on 2022-02-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0003_auto_20220210_0416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToModule',
        ),
    ]
