# Generated by Django 3.2 on 2022-01-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0003_auto_20220120_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True)),
                ('op1', models.CharField(max_length=200, null=True)),
                ('op2', models.CharField(max_length=200, null=True)),
                ('op3', models.CharField(max_length=200, null=True)),
                ('op4', models.CharField(max_length=200, null=True)),
                ('ans', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
