# Generated by Django 3.2 on 2022-01-22 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0004_questionsmod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(max_length=500)),
                ('op1', models.CharField(max_length=300)),
                ('op2', models.CharField(max_length=300)),
                ('op3', models.CharField(max_length=300)),
                ('op4', models.CharField(max_length=300)),
                ('answ', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionsMod',
        ),
        migrations.AddField(
            model_name='tests',
            name='module_sel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testBuilder.modules'),
        ),
        migrations.AddField(
            model_name='tests',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='test_sel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testBuilder.tests'),
        ),
    ]
