# Generated by Django 3.2 on 2022-01-22 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0005_auto_20220122_0727'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modules',
            new_name='Module',
        ),
        migrations.RenameModel(
            old_name='Tests',
            new_name='Test',
        ),
    ]
