# Generated by Django 3.2 on 2022-02-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0006_alter_quiz_answ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answ',
            field=models.CharField(choices=[('option1', 'Answer Option 1'), ('option2', 'Answer Option 2'), ('option3', 'Answer Option 3'), ('option4', 'Answer Option 4')], default='', max_length=7),
        ),
    ]
