# Generated by Django 3.2 on 2022-01-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0006_auto_20220122_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
