# Generated by Django 3.2 on 2022-01-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0007_module_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='name',
        ),
        migrations.AlterField(
            model_name='module',
            name='module_name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
