# Generated by Django 3.2 on 2022-02-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0007_alter_quiz_answ'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='userAnsw',
            field=models.CharField(default='', max_length=10),
        ),
    ]
