# Generated by Django 3.2 on 2022-02-10 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testBuilder', '0009_remove_quizresult_useransw'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_desc',
            field=models.TextField(help_text='Resize textbox by dragging bottom right corner icon, if needed', max_length=300),
        ),
    ]
