# Generated by Django 3.2 on 2022-01-23 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0009_auto_20220122_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='answ',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='op1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='op2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='op3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='op4',
        ),
    ]
