# Generated by Django 3.2 on 2022-01-25 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0010_auto_20220123_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answ',
            field=models.CharField(default='', help_text='Input option1 for the first option, option2 for the second option', max_length=300),
        ),
        migrations.AddField(
            model_name='quiz',
            name='op1',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='quiz',
            name='op2',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='quiz',
            name='op3',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='quiz',
            name='op4',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quest',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.CreateModel(
            name='quizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('wrong', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('linked_quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testBuilder.quiz')),
                ('linked_test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testBuilder.test')),
            ],
        ),
    ]
