# Generated by Django 3.2 on 2022-02-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0010_auto_20220211_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='lettergrade',
            field=models.CharField(default='', max_length=10),
        ),
    ]
