# Generated by Django 3.2 on 2022-01-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0011_auto_20220125_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='linked_quiz',
        ),
    ]
