# Generated by Django 3.2 on 2022-02-14 17:45

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0011_quizresult_lettergrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_desc',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quest',
            field=django_quill.fields.QuillField(),
        ),
    ]
