# Generated by Django 3.2 on 2022-01-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0012_remove_quizresult_linked_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='linked_test',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='grade',
            field=models.CharField(default='', max_length=10),
        ),
    ]
