# Generated by Django 3.2 on 2022-02-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0012_auto_20220215_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quest',
            field=models.CharField(default='', max_length=500),
        ),
    ]
