# Generated by Django 3.2 on 2022-01-25 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testBuilder', '0013_auto_20220125_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='attempted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='correct',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='percentage',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='total',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='wrong',
            field=models.CharField(default='', max_length=10),
        ),
    ]
