# Generated by Django 3.2 on 2022-02-14 18:13

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0013_alter_quiz_quest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quest',
            field=django_quill.fields.QuillField(),
        ),
    ]
