# Generated by Django 3.2 on 2022-01-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0014_auto_20220125_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='attempted_by',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='score',
        ),
    ]
