# Generated by Django 3.2 on 2022-02-14 18:32

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0014_alter_quiz_quest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quest',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='op1',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='op2',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='op3',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='op4',
            field=django_quill.fields.QuillField(),
        ),
    ]
