# Generated by Django 3.2 on 2022-02-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0015_auto_20220215_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quest',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='op1',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='op2',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='op3',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='op4',
            field=models.CharField(default='', max_length=300),
        ),
    ]
