# Generated by Django 3.2 on 2022-01-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0016_auto_20220126_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='correct',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='grade',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='percentage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='wrong',
            field=models.IntegerField(),
        ),
    ]
