# Generated by Django 3.2 on 2022-01-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0017_auto_20220126_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='wrong',
            field=models.IntegerField(default=0),
        ),
    ]
