# Generated by Django 3.2 on 2022-02-15 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0018_auto_20220215_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='linked_module',
        ),
    ]
