# Generated by Django 3.2 on 2022-02-15 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0020_quizresult_linked_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='linked_module',
        ),
        migrations.AddField(
            model_name='quiz',
            name='linked_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testBuilder.module'),
        ),
    ]
