# Generated by Django 3.2 on 2022-01-26 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testBuilder', '0020_auto_20220126_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='attempted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='linked_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testBuilder.module'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='linked_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testBuilder.test'),
        ),
    ]
