# Generated by Django 3.2 on 2022-01-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0021_auto_20220126_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='attempted_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
