# Generated by Django 3.2 on 2022-01-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0022_quizresult_attempted_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='a_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='attempted_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
