# Generated by Django 3.2 on 2022-02-08 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0023_auto_20220127_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='test_sel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testBuilder.test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='module_sel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testBuilder.module'),
        ),
    ]
