# Generated by Django 3.2 on 2022-02-08 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testBuilder', '0025_alter_quiz_answ'),
    ]

    operations = [
        migrations.CreateModel(
            name='addUserModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('module_linked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testBuilder.module')),
            ],
        ),
    ]
