# Generated by Django 3.2 on 2022-02-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0027_auto_20220208_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='a_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='attempted_time',
            field=models.DateTimeField(),
        ),
    ]
