# Generated by Django 3.2 on 2022-02-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0029_remove_quizresult_a_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_date',
            field=models.DateTimeField(),
        ),
    ]
