# Generated by Django 3.2 on 2022-02-08 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0030_alter_test_test_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='linked_module',
        ),
    ]
