# Generated by Django 3.2 on 2022-02-08 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testBuilder', '0023_auto_20220127_0607'),
        ('buildAssign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('grade', models.CharField(default='', max_length=10)),
                ('a_time', models.DateTimeField(auto_now=True)),
                ('attempted_time', models.DateTimeField(auto_now_add=True)),
                ('attempted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('linked_assign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildAssign.assignment')),
                ('linked_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testBuilder.module')),
            ],
        ),
    ]
