# Generated by Django 3.2 on 2022-02-09 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testBuilder', '0005_alter_module_host'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buildAssign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='linked_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testBuilder.module'),
        ),
        migrations.AlterField(
            model_name='assignresult',
            name='attempted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignresult',
            name='linked_assign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildAssign.assignment'),
        ),
        migrations.AlterField(
            model_name='assignresult',
            name='linked_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testBuilder.module'),
        ),
    ]
