# Generated by Django 3.2 on 2022-02-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildAssign', '0003_auto_20220211_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
