# Generated by Django 3.2 on 2022-02-11 06:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buildAssign', '0007_answer_upload_txt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='upload_txt',
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_txt', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['txt'])])),
                ('link_answ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildAssign.answer')),
                ('link_assign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildAssign.assignment')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
