# Generated by Django 3.2 on 2022-02-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildAssign', '0008_auto_20220211_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='limit',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
