# Generated by Django 3.2 on 2022-02-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildAssign', '0010_alter_answer_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='limit',
            field=models.IntegerField(default=''),
        ),
    ]
