# Generated by Django 3.2 on 2022-02-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildAssign', '0011_alter_answer_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='limit',
        ),
        migrations.AddField(
            model_name='assignment',
            name='limit',
            field=models.IntegerField(null=True),
        ),
    ]
