# Generated by Django 3.2 on 2022-02-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildAssign', '0012_auto_20220211_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='limit',
            field=models.CharField(choices=[('1', '1'), ('0', '0')], default='1', max_length=1),
        ),
    ]
