# Generated by Django 3.2 on 2022-02-11 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildAssign', '0013_alter_assignment_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='limit',
        ),
    ]
