# Generated by Django 3.2 on 2022-02-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildAssign', '0014_remove_assignment_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignresult',
            name='lettergrade',
            field=models.CharField(default='', max_length=10),
        ),
    ]
