# Generated by Django 3.2 on 2022-02-14 14:25

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buildAssign', '0015_assignresult_lettergrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='set_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=django_quill.fields.QuillField(default='ici'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=django_quill.fields.QuillField(default='ici'),
        ),
    ]
