# Generated by Django 3.2 on 2022-02-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildAssign', '0017_auto_20220215_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
