# Generated by Django 3.2 on 2022-02-14 19:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('buildAssign', '0018_alter_answer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=tinymce.models.HTMLField(),
        ),
    ]
